set_property PACKAGE_PIN Y21 [get_ports {blue[0]}]
set_property PACKAGE_PIN Y20 [get_ports {blue[1]}]
set_property PACKAGE_PIN AB20 [get_ports {blue[2]}]
set_property PACKAGE_PIN AB19 [get_ports {blue[3]}]
set_property PACKAGE_PIN AB22 [get_ports {green[0]}]
set_property PACKAGE_PIN AA22 [get_ports {green[1]}]
set_property PACKAGE_PIN AB21 [get_ports {green[2]}]
set_property PACKAGE_PIN AA21 [get_ports {green[3]}]
set_property PACKAGE_PIN V20 [get_ports {red[0]}]
set_property PACKAGE_PIN U20 [get_ports {red[1]}]
set_property PACKAGE_PIN V19 [get_ports {red[2]}]
set_property PACKAGE_PIN V18 [get_ports {red[3]}]
set_property PACKAGE_PIN AA19 [get_ports {hsync}]
set_property PACKAGE_PIN Y19 [get_ports {vsync}]

set_property PACKAGE_PIN T18 [get_ports {BTNU}]
set_property PACKAGE_PIN R16 [get_ports {BTND}]
set_property PACKAGE_PIN N15 [get_ports {BTNL}]
set_property PACKAGE_PIN R18 [get_ports {BTNR}]
set_property PACKAGE_PIN P16 [get_ports {BTNC}]

set_property PACKAGE_PIN Y9 [get_ports {clk}]

set_property IOSTANDARD LVCMOS33 [get_ports {clk hsync vsync red[*] green[*] blue[*]}]
set_property IOSTANDARD LVCMOS25 [get_ports {BTNU BTND BTNL BTNR BTNC}]
create_clock -name sys_clk -period 10.000 [get_ports {clk}]
